name: 'Graduate Day Push'

on:
  push:
  schedule:
      - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/cache@v2
        id: cache-python
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        run: python GraduateDayPush.py ${{ secrets.BARK_KEY }} ${{ secrets.BARK_SJ }}
